<a href="https://colab.research.google.com/github/ArijeetGoswami/FAKE-NEWS-DETECTOR/blob/main/FAKE_NEWS_DETECTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#lets import the libraries
import pandas as pd
import numpy as np


In [2]:
              # data-collection
#lets read the data-set by declaring data-frame (true and fake) for true and fake dataset
true = pd.read_csv('/content/True.csv')
fake = pd.read_csv('/content/Fake.csv')

In [3]:
#lets check the data-set
true.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

In [4]:
fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [5]:
#lets create a cloumn in the true and fake dataset to provide that this content of data is true or false (1,0)
true['target'] = 1
fake['target'] = 0

In [6]:
#view of data-set
true.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  target  
0  December 31, 2017        1  
1  December 29, 2017        1  
2  December 31, 2017        1  
3  December 30, 2017        1  
4  December 29, 2017        1

In [7]:
fake.head()


title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  target  
0  December 31, 2017       0  
1  December 31, 2017       0  
2  December 30, 2017       0  
3  December 29, 2017       0  
4  December 25, 2017       0

In [8]:
#lets conacatenate the data-set of true and fake
news = pd.concat([true,fake],axis=0)

In [9]:
#lets view
news.head()    #true news data-set view

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  target  
0  December 31, 2017        1  
1  December 29, 2017        1  
2  December 31, 2017        1  
3  December 30, 2017        1  
4  December 29, 2017        1

In [10]:
news.tail()   #fake news data-set view

title  \
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   

                                                    text      subject  \
23476  21st Century Wire says As 21WIRE reported earl...  Middle-east   
23477  21st Century Wire says It s a familiar theme. ...  Middle-east   
23478  Patrick Henningsen  21st Century WireRemember ...  Middle-east   
23479  21st Century Wire says Al Jazeera America will...  Middle-east   
23480  21st Century Wire says As 21WIRE predicted in ...  Middle-east   

                   date  target  
23476  January 16, 2016       0  
23477  January 16, 2016       0  
23478  January 15, 2016       0  
23479  January 14, 2016       0  
23480  January 12, 2016       0

In [11]:
#before lets delete the useless column not required for the data-sey
news = news.drop(['title','subject','date'],axis=1)

In [12]:
#lets check the new form of data-set
news.head()

text  target
0  WASHINGTON (Reuters) - The head of a conservat...       1
1  WASHINGTON (Reuters) - Transgender people will...       1
2  WASHINGTON (Reuters) - The special counsel inv...       1
3  WASHINGTON (Reuters) - Trump campaign adviser ...       1
4  SEATTLE/WASHINGTON (Reuters) - President Donal...       1

In [13]:
# @title as we cana see the the true news is preset in the top most level of the data-set and fake news present at down level of the news data-set


In [14]:
#                     data preprocessing
#lets reshuffle the data-set
news = news.sample(frac=1)

In [15]:
news.head()

text  target
7407   WASHINGTON (Reuters) - President Barack Obama ...       1
16710  ISLAMABAD (Reuters) - Ties between the United ...       1
3576   BRUSSELS (Reuters) - U.S. President Donald Tru...       1
13679  A Californian with a gun and a Trump sign in h...       0
16840  MUMBAI (Reuters) - India s central bank on Sat...       1

In [16]:
news.reset_index(inplace=True) #cerating an index column

In [17]:
news.head()

index                                               text  target
0   7407  WASHINGTON (Reuters) - President Barack Obama ...       1
1  16710  ISLAMABAD (Reuters) - Ties between the United ...       1
2   3576  BRUSSELS (Reuters) - U.S. President Donald Tru...       1
3  13679  A Californian with a gun and a Trump sign in h...       0
4  16840  MUMBAI (Reuters) - India s central bank on Sat...       1

In [18]:
#cleaning of data
#lets remove the index as its of no use
news.drop(['index'],axis=1, inplace = True)

In [19]:
#lets check data-set
news.head()

text  target
0  WASHINGTON (Reuters) - President Barack Obama ...       1
1  ISLAMABAD (Reuters) - Ties between the United ...       1
2  BRUSSELS (Reuters) - U.S. President Donald Tru...       1
3  A Californian with a gun and a Trump sign in h...       0
4  MUMBAI (Reuters) - India s central bank on Sat...       1

In [20]:
# @title our data is read


In [21]:
#      data-future extraction
import re # covent text into readable form


In [22]:
#lets defie the function
def wordopt(text):    #fuction = wordopt with respect to text column of the data-set
  text = text.lower()

  #removing the html tag
  text = re.sub('\[.*?\]', '', text)

  #remopving punctuation
  text = re.sub("\\W"," ",text)

  #removing the urls
  text = re.sub('https?://\S+|www\.\S+', '', text)

  #remove the didgits
  text = re.sub('\d', '', text)

  return text

In [23]:
news['text'].apply(wordopt)   #here we are applying the wordopt fuction with respect to the text column og the news data set

0        washington  reuters    president barack obama ...
1        islamabad  reuters    ties between the united ...
2        brussels  reuters    u s  president donald tru...
3        a californian with a gun and a trump sign in h...
4        mumbai  reuters    india s central bank on sat...
                               ...                        
44893    well  it s happened  in the manner of every ot...
44894    washington  reuters    republican u s  preside...
44895    sacramento  calif   reuters    california lead...
44896    washington  reuters    the house of representa...
44897    washington  reuters    a vote by u s  house re...
Name: text, Length: 44898, dtype: object

In [24]:
#lets declare the x and y parameters for training and  testing the data-set
x = news['text']
y = news['target']

In [25]:
from sklearn.model_selection import train_test_split

#now lets do the opration
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)      #operation done with respect to size to 30%


In [26]:
#lets check the shape
x_train.shape

(31428,)

In [27]:
y_train.shape

(31428,)

In [28]:
#lets create vectors for the ml model
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
vector = TfidfVectorizer()

In [30]:
#now lests work on the oprtaion of vector with respect x and y values
xv_train = vector.fit_transform(x_train)

#lest sort the data-set
xv_test = vector.transform(x_test)

In [31]:
xv_train


<31428x105395 sparse matrix of type '<class 'numpy.float64'>'
	with 6561762 stored elements in Compressed Sparse Row format>

In [32]:
xv_test

<13470x105395 sparse matrix of type '<class 'numpy.float64'>'
	with 2816837 stored elements in Compressed Sparse Row format>

In [33]:
# now after performing the vectors for the x and y variables now lets
#lets import the ml model


In [34]:
#logistic regression
import sklearn.linear_model as LogisticRegression
LR = LogisticRegression.LogisticRegression()


In [35]:
#lets fit for the vectors xv_trian and xv_test
LR.fit(xv_train,y_train)

LogisticRegression()

In [36]:
#lets predict the value for the logistic regression XV_test vector
LR.predict(xv_test)

array([0, 1, 0, ..., 0, 1, 0])

In [37]:
#lets see the score
LR.score(xv_test,y_test)              #value is recoginze upto to 98%  preety ggod score for the model

0.9856718634001485

In [38]:
# @title decision tree clasisfier
#decision tree classifier


In [39]:
import sklearn.tree as DecisionTreeClassifier
DT = DecisionTreeClassifier.DecisionTreeClassifier()

In [40]:
#LETS fit the vector into th DT model
DT.fit(xv_train,y_train)

DecisionTreeClassifier()

In [41]:
#predict the DTC as array or not
DT.predict(xv_test)

array([0, 1, 0, ..., 0, 1, 0])

In [42]:
#predic the score for DT model
DT.score(xv_test,y_test)         # value is upto 99% preety a good score

0.9951002227171493

In [43]:
# @title Random forest tree

In [44]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()

#lets fit the vecors (X,Y) to the RF
RF.fit(xv_train,y_train)                 #take tooo much time for fitting the data-set in the randomforestclassifier

RandomForestClassifier()

In [45]:
#lets predict the RF
RF.predict(xv_test)

array([0, 1, 0, ..., 0, 1, 0])

In [46]:
#lets see the score for the model
RF.score(xv_test,y_test)         #98% successful

0.987750556792873

In [47]:
# lets check the prediction model
def output_lable(n):
  if n == 0:
    return "Fake News"
  elif n == 1:
    return "Not A Fake News"

In [48]:
#lets declare the another function for manual testing of the data
def manual_testing(news):
    testing_news = {"text": [news]} #corrected sytax for defining dictionary
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)
    new_x_test = new_def_test["text"]
    new_xv_test = vector.transform(new_x_test)
    #prdicted values
    pred_LR = LR.predict(new_xv_test)
    pred_DT = DT.predict(new_xv_test)
    pred_RF = RF.predict(new_xv_test)

    return ("\n\nLR Prediction: {} \nDT Prediction: {} \nRF Prediction: {}".format(output_lable(pred_LR[0]), output_lable(pred_DT[0]), output_lable(pred_RF[0])))

In [49]:
news_article = str(input())
manual_testing(news_article)


KeyboardInterrupt: Interrupted by user